-- Agrega linkVideo a Receta y RecetaPlantilla: un link directo a una
-- busqueda dentro del canal de YouTube de Alvaro Barrientos Montero para
-- esa receta (no se referencia un video puntual porque no hay forma de
-- confirmar que exista uno especifico para cada plato -- la busqueda
-- dentro del canal siempre es un link real y util).
ALTER TABLE "RecetaPlantilla" ADD COLUMN "linkVideo" TEXT;
ALTER TABLE "Receta" ADD COLUMN "linkVideo" TEXT;

-- Backfill de las 10 recetas sugeridas ya existentes.
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Arroz+con+pollo' WHERE id = 'b742a3e4-4e8c-4025-a956-0c70e2a3857b';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Porotos+granados' WHERE id = '556fde97-62ea-47f9-bbcd-a1107fcf46e3';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Ensalada+C%C3%A9sar' WHERE id = '459702fd-5f5f-4d70-87d9-1ef0714c4ddb';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Pasta+napolitana' WHERE id = 'e619365a-1a5d-4a8b-9065-1412e00e9445';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Tacos+de+carne' WHERE id = 'e7b5c79d-9a2e-4fd0-af5b-b8b914450e50';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Sopaipillas' WHERE id = 'd9eb5ac9-3e7b-4bd6-ac13-8f7c480f1d39';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Salm%C3%B3n+al+horno+con+verduras' WHERE id = '995b9d95-ecfe-4394-a30b-9ed11bd0b262';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Lentejas+guisadas' WHERE id = 'b19c48b3-2b1c-43f6-a973-4660a2e8f6bf';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Omelette+de+verduras' WHERE id = 'df493fff-6751-473b-bd75-ceafebada52c';
UPDATE "RecetaPlantilla" SET "linkVideo" = 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Cazuela+de+vacuno' WHERE id = 'f7ef3bed-1f35-4543-adf2-0ce6a1eefb53';

INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('66ab81a5-5e10-424f-a45d-316359dac89f', 'Pan amasado casero', ARRAY['desayuno'], 90, 8, '[{"n":"Harina","cat":"abarrotes"},{"n":"Manteca","cat":"abarrotes"},{"n":"Levadura","cat":"abarrotes"},{"n":"Sal","cat":"abarrotes"}]'::jsonb, ARRAY['Disolver la levadura en agua tibia', 'Mezclar la harina con la manteca y la sal', 'Amasar hasta lograr una masa elástica', 'Dejar reposar hasta que duplique su tamaño', 'Formar los panes y hornear a 200°C 20 minutos'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Pan+amasado+casero');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('76a824cb-6ccf-4a38-acf3-1aa963df4678', 'Huevos revueltos con jamón y queso', ARRAY['desayuno'], 10, 2, '[{"n":"Huevos","cat":"proteinas"},{"n":"Jamón","cat":"proteinas"},{"n":"Queso","cat":"lacteos"},{"n":"Mantequilla","cat":"lacteos"}]'::jsonb, ARRAY['Batir los huevos', 'Picar el jamón en cubos pequeños', 'Derretir mantequilla en la sartén', 'Cocinar los huevos revolviendo, agregar jamón y queso al final'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Huevos+revueltos+con+jam%C3%B3n+y+queso');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('c7679415-3691-4bd1-bf2c-503c117276c8', 'Tostadas francesas', ARRAY['desayuno'], 15, 4, '[{"n":"Pan de molde","cat":"abarrotes"},{"n":"Huevos","cat":"proteinas"},{"n":"Leche","cat":"lacteos"},{"n":"Canela","cat":"abarrotes"},{"n":"Azúcar","cat":"abarrotes"}]'::jsonb, ARRAY['Batir los huevos con la leche, azúcar y canela', 'Remojar el pan en la mezcla', 'Cocinar en sartén con mantequilla hasta dorar ambos lados'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Tostadas+francesas');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('67ab9649-f5de-47ec-aabd-a510e412d958', 'Yogurt con granola y frutas', ARRAY['desayuno'], 5, 2, '[{"n":"Yogurt","cat":"lacteos"},{"n":"Granola","cat":"abarrotes"},{"n":"Plátano","cat":"verduras"},{"n":"Miel","cat":"abarrotes"}]'::jsonb, ARRAY['Servir el yogurt en un bowl', 'Agregar la granola y la fruta picada', 'Rociar con miel'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Yogurt+con+granola+y+frutas');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('b3c5b218-848c-43d1-bf6f-8e59a5aa24f5', 'Pollo al horno con papas', ARRAY['almuerzo'], 70, 4, '[{"n":"Pollo entero","cat":"proteinas"},{"n":"Papas","cat":"verduras"},{"n":"Ajo","cat":"verduras"},{"n":"Romero","cat":"abarrotes"},{"n":"Aceite de oliva","cat":"abarrotes"}]'::jsonb, ARRAY['Precalentar el horno a 200°C', 'Sazonar el pollo con ajo, romero, sal y aceite', 'Disponer el pollo con las papas en una bandeja', 'Hornear 60 minutos hasta dorar'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Pollo+al+horno+con+papas');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('4ad724ea-3e38-4332-9e89-c50052ad5859', 'Charquicán', ARRAY['almuerzo'], 50, 4, '[{"n":"Carne molida","cat":"proteinas"},{"n":"Zapallo","cat":"verduras"},{"n":"Papas","cat":"verduras"},{"n":"Choclo","cat":"verduras"},{"n":"Cebolla","cat":"verduras"}]'::jsonb, ARRAY['Sofreír la cebolla y la carne molida', 'Agregar el zapallo y las papas en cubos con agua', 'Cocinar hasta que las verduras estén blandas y se deshagan', 'Incorporar el choclo al final'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Charquic%C3%A1n');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('46743789-be34-4242-a70f-8e32fc41b0f6', 'Pastel de choclo', ARRAY['almuerzo'], 80, 6, '[{"n":"Choclo molido","cat":"verduras"},{"n":"Carne molida","cat":"proteinas"},{"n":"Pollo","cat":"proteinas"},{"n":"Cebolla","cat":"verduras"},{"n":"Huevo duro","cat":"proteinas"},{"n":"Aceitunas","cat":"abarrotes"}]'::jsonb, ARRAY['Preparar el pino sofriendo cebolla con carne y pollo', 'Disponer el pino en fuentes con huevo duro y aceitunas', 'Cubrir con el choclo molido', 'Hornear a 200°C hasta dorar la superficie'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Pastel+de+choclo');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('9b3e6d9a-8188-4cc1-9b1e-5aa12c2839a9', 'Merluza frita con puré', ARRAY['almuerzo'], 35, 4, '[{"n":"Merluza","cat":"proteinas"},{"n":"Harina","cat":"abarrotes"},{"n":"Papas","cat":"verduras"},{"n":"Leche","cat":"lacteos"},{"n":"Mantequilla","cat":"lacteos"}]'::jsonb, ARRAY['Pasar los filetes de merluza por harina', 'Freír hasta dorar por ambos lados', 'Cocinar las papas y hacer puré con leche y mantequilla', 'Servir juntos'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Merluza+frita+con+pur%C3%A9');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('f65f9141-55cb-413b-90c5-d07a5824234b', 'Estofado de vacuno', ARRAY['almuerzo'], 90, 4, '[{"n":"Posta de vacuno","cat":"proteinas"},{"n":"Zanahoria","cat":"verduras"},{"n":"Papas","cat":"verduras"},{"n":"Vino tinto","cat":"abarrotes"},{"n":"Cebolla","cat":"verduras"}]'::jsonb, ARRAY['Dorar la carne en trozos', 'Sofreír la cebolla y la zanahoria', 'Agregar el vino y dejar reducir', 'Añadir las papas y cocinar a fuego lento 1 hora'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Estofado+de+vacuno');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('688d7dca-8293-415c-a0d0-50d0f1e6ad73', 'Arroz a la jardinera', ARRAY['almuerzo'], 30, 4, '[{"n":"Arroz","cat":"abarrotes"},{"n":"Zanahoria","cat":"verduras"},{"n":"Arvejas","cat":"verduras"},{"n":"Pimentón","cat":"verduras"},{"n":"Cebolla","cat":"verduras"}]'::jsonb, ARRAY['Sofreír la cebolla, zanahoria y pimentón', 'Agregar el arroz y sofreír 2 minutos', 'Incorporar el caldo y las arvejas', 'Cocinar tapado hasta que el arroz esté listo'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Arroz+a+la+jardinera');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('62af80c0-2bab-48bd-bb77-3fdff782fdc8', 'Sopa de verduras', ARRAY['cena'], 35, 4, '[{"n":"Zapallo","cat":"verduras"},{"n":"Zanahoria","cat":"verduras"},{"n":"Papas","cat":"verduras"},{"n":"Apio","cat":"verduras"},{"n":"Caldo de verduras","cat":"abarrotes"}]'::jsonb, ARRAY['Picar todas las verduras', 'Cocinar en el caldo hasta que estén blandas', 'Moler si se prefiere una sopa crema'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Sopa+de+verduras');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('d2b2dd43-d5b3-4fe9-b22e-16569ef48fdd', 'Quesadillas de queso', ARRAY['cena'], 15, 2, '[{"n":"Tortillas","cat":"abarrotes"},{"n":"Queso","cat":"lacteos"},{"n":"Jamón","cat":"proteinas"}]'::jsonb, ARRAY['Rellenar las tortillas con queso y jamón', 'Cocinar en sartén hasta que el queso se derrita y doren ambos lados'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Quesadillas+de+queso');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('666b494c-a1d9-4b0d-a66e-71e084e11e3f', 'Pizza casera', ARRAY['cena'], 60, 4, '[{"n":"Masa de pizza","cat":"abarrotes"},{"n":"Salsa de tomate","cat":"abarrotes"},{"n":"Queso mozzarella","cat":"lacteos"},{"n":"Jamón","cat":"proteinas"},{"n":"Orégano","cat":"abarrotes"}]'::jsonb, ARRAY['Estirar la masa', 'Cubrir con salsa de tomate, queso y jamón', 'Espolvorear orégano', 'Hornear a 220°C 15 minutos'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Pizza+casera');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('68684965-b411-457c-9033-61686aa09114', 'Arroz con leche', ARRAY['postre'], 40, 4, '[{"n":"Arroz","cat":"abarrotes"},{"n":"Leche","cat":"lacteos"},{"n":"Azúcar","cat":"abarrotes"},{"n":"Canela","cat":"abarrotes"}]'::jsonb, ARRAY['Cocinar el arroz en agua hasta ablandar', 'Agregar la leche, el azúcar y la canela', 'Cocinar a fuego lento revolviendo hasta espesar'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Arroz+con+leche');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('dbc02dcc-6ac0-4f5b-b029-01e71a574d50', 'Mote con huesillo', ARRAY['postre'], 30, 4, '[{"n":"Mote","cat":"abarrotes"},{"n":"Huesillos","cat":"abarrotes"},{"n":"Azúcar","cat":"abarrotes"},{"n":"Canela","cat":"abarrotes"}]'::jsonb, ARRAY['Remojar los huesillos la noche anterior', 'Cocinar los huesillos con azúcar y canela en su jugo', 'Cocinar el mote aparte', 'Mezclar y servir frío'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Mote+con+huesillo');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('ee83d903-89c8-443a-8738-d19753981f96', 'Flan de vainilla', ARRAY['postre'], 60, 6, '[{"n":"Leche condensada","cat":"abarrotes"},{"n":"Huevos","cat":"proteinas"},{"n":"Leche","cat":"lacteos"},{"n":"Esencia de vainilla","cat":"abarrotes"},{"n":"Azúcar","cat":"abarrotes"}]'::jsonb, ARRAY['Hacer un caramelo con azúcar y cubrir el molde', 'Batir la leche condensada, huevos, leche y vainilla', 'Verter en el molde y cocinar a baño maría al horno 45 minutos', 'Enfriar antes de desmoldar'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Flan+de+vainilla');
INSERT INTO "RecetaPlantilla" (id, nombre, tipos, "tiempoMin", porciones, ingredientes, pasos, "linkVideo") VALUES
('16238480-34b6-43c9-a2f6-02e20425c215', 'Kuchen de manzana', ARRAY['postre'], 60, 8, '[{"n":"Harina","cat":"abarrotes"},{"n":"Mantequilla","cat":"lacteos"},{"n":"Azúcar","cat":"abarrotes"},{"n":"Manzanas","cat":"verduras"},{"n":"Huevos","cat":"proteinas"}]'::jsonb, ARRAY['Preparar una masa con harina, mantequilla, azúcar y huevo', 'Estirar en un molde', 'Cubrir con láminas de manzana', 'Hornear a 180°C 40 minutos'], 'https://www.youtube.com/@AlvaroBarrientosMontero/search?query=Kuchen+de+manzana');
